<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*" />
    <PackageReference Include="Moq" Version="4.*" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.*" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.*" />
    <PackageReference Include="MassTransit.TestFramework" Version="8.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\gateway\LMS.Gateway\LMS.Gateway.csproj" />
    <ProjectReference Include="..\..\src\services\LMS.IdentityService\LMS.IdentityService.Api\LMS.IdentityService.Api.csproj" />
    <ProjectReference Include="..\..\src\services\LMS.CourseService\LMS.CourseService.Api\LMS.CourseService.Api.csproj" />
    <ProjectReference Include="..\..\src\services\LMS.CourseService\LMS.CourseService.Domain\LMS.CourseService.Domain.csproj" />
    <ProjectReference Include="..\..\src\services\LMS.ContentService\LMS.ContentService.Domain\LMS.ContentService.Domain.csproj" />
    <ProjectReference Include="..\..\src\services\LMS.ContentService\LMS.ContentService.Api\LMS.ContentService.Api.csproj" />
    <ProjectReference Include="..\..\src\services\LMS.EnrollmentService\LMS.EnrollmentService.Api\LMS.EnrollmentService.Api.csproj" />
    <ProjectReference Include="..\..\src\services\LMS.EnrollmentService\LMS.EnrollmentService.Domain\LMS.EnrollmentService.Domain.csproj" />
    <ProjectReference Include="..\..\src\LMS.Contracts\LMS.Contracts.csproj" />
  </ItemGroup>
</Project>
