<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.2" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.*" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="9.4.1-preview.1.25408.4" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="9.*" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.*" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.*" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="9.*" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.*" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="9.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../gateway/LMS.Gateway/LMS.Gateway.csproj" />
    <ProjectReference Include="../services/LMS.IdentityService/LMS.IdentityService.Api/LMS.IdentityService.Api.csproj" />
    <ProjectReference Include="../services/LMS.IdentityService/LMS.IdentityService.Migrator/LMS.IdentityService.Migrator.csproj" />
    <ProjectReference Include="../services/LMS.CourseService/LMS.CourseService.Api/LMS.CourseService.Api.csproj" />
    <ProjectReference Include="../services/LMS.CourseService/LMS.CourseService.Migrator/LMS.CourseService.Migrator.csproj" />
    <ProjectReference Include="../services/LMS.ContentService/LMS.ContentService.Api/LMS.ContentService.Api.csproj" />
    <ProjectReference Include="../services/LMS.ContentService/LMS.ContentService.Worker/LMS.ContentService.Worker.csproj" />
    <ProjectReference Include="..\services\LMS.EnrollmentService\LMS.EnrollmentService.Api\LMS.EnrollmentService.Api.csproj" />
    <ProjectReference Include="..\services\LMS.EnrollmentService\LMS.EnrollmentService.Migrator\LMS.EnrollmentService.Migrator.csproj" />
    <ProjectReference Include="..\services\LMS.ProgressService\LMS.ProgressService.Api\LMS.ProgressService.Api.csproj" />
    <ProjectReference Include="..\services\LMS.ProgressService\LMS.ProgressService.Migrator\LMS.ProgressService.Migrator.csproj" />
    <ProjectReference Include="..\services\LMS.AssessmentService\LMS.AssessmentService.Api\LMS.AssessmentService.Api.csproj" />
    <ProjectReference Include="..\services\LMS.AssessmentService\LMS.AssessmentService.Migrator\LMS.AssessmentService.Migrator.csproj" />
  </ItemGroup>
</Project>
