<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LMS.AssessmentService.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" Version="9.3.0" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.3.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.1" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LMS.AssessmentService.Infrastructure\LMS.AssessmentService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\LMS.ServiceDefaults\LMS.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
